export const productTypes = {
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCES",
  GET_PRODUCT_LOADING: "GET_PRODUCT_LOADING",
  GET_PRODUCT_FAILURE: "GET_PRODUCT_LOADING",
  SET_FLAVOUR: "SET_FLAVOUR",
  SET_QTY: "SET_QTY",
  SET_SLUG: "SET_SLUG",
  RESET_REDUCER: "RESET_REDUCER",
};
